name: pyromancy2023
recipe: wordpress
config:
    webroot: web
services:
    appserver:
        type: php:8.1 # Bedrock requires PHP >= 8.0
    phpmyadmin:
        type: phpmyadmin
proxy:
    sqlmyproject:
        - phpmyadmin.lndo.site
