import {
  defineConfig,
  presetTypography,
  transformerVariantGroup,
  presetWind3,
  presetIcons,
} from "unocss";
import { tailwindOKLCHColorsPreset } from "./src/presets/tailwind-oklch-colors-preset";
import { gbtPreset } from "./src/presets/index.js";
console.log("colors", gbtPreset());
export default defineConfig({
  presets: [
    presetWind3({
      preflight: true,
      dark: "class",
    }),
    tailwindOKLCHColorsPreset(),
    presetTypography(),
    gbtPreset(),
    presetIcons({}),
  ],

  transformers: [transformerVariantGroup()],

  // Simplified content detection - UnoCSS will scan all files by default
  content: {
    filesystem: ["./index.html", "./src/**/*.{html,js,ts,jsx,tsx}"],
  },

  // Safelist to ensure custom colors are always available
  safelist: [
    // Custom colors from _base.ts
    "bg-gordons-green",
    "text-gordons-green",
    "border-gordons-green",
    "bg-astra",
    "text-astra",
    "border-astra",
    "bg-coral-tree",
    "text-coral-tree",
    "border-coral-tree",
    "bg-sepia-black",
    "text-sepia-black",
    "border-sepia-black",
    "bg-pohutukawa",
    "text-pohutukawa",
    "border-pohutukawa",
    "bg-mirage",
    "text-mirage",
    "border-mirage",
    "bg-tana",
    "text-tana",
    "border-tana",
    "bg-spice",
    "text-spice",
    "border-spice",
    "bg-highball",
    "text-highball",
    "border-highball",
    "bg-west-coast",
    "text-west-coast",
    "border-west-coast",
    "bg-jacko-bean",
    "text-jacko-bean",
    "border-jacko-bean",
    "bg-sandstone",
    "text-sandstone",
    "border-sandstone",
    "bg-schooner",
    "text-schooner",
    "border-schooner",
    "bg-ironside-gray",
    "text-ironside-gray",
    "border-ironside-gray",
    "bg-crowshead",
    "text-crowshead",
    "border-crowshead",
    "bg-onion",
    "text-onion",
    "border-onion",
    "bg-madras",
    "text-madras",
    "border-madras",
    "bg-corn",
    "text-corn",
    "border-corn",
    "bg-gumleaf",
    "text-gumleaf",
    "border-gumleaf",

    // Legacy custom colors
    "to-my-coral",
    "bg-oklch-green",
    "text-oklch-green",
    "from-oklch-green",
    "to-oklch-green",
    "bg-oklch-mint",
    "from-oklch-mint",
    "to-oklch-mint",

    // Add all color combinations that might be used dynamically
    ...[
      "red",
      "orange",
      "yellow",
      "lime",
      "green",
      "emerald",
      "teal",
      "cyan",
      "sky",
      "blue",
      "indigo",
      "purple",
      "pink",
      "rose",
    ].flatMap((color) =>
      [50, 100, 200, 300, 400, 500, 600, 700, 800, 900].map(
        (shade) => `bg-${color}-${shade}`,
      ),
    ),

    // Standard colors (now forced to OKLCH)
    "bg-lime-500",
    "from-lime-500",
    "from-lime-600",
    "to-lime-500",
    "to-lime-300",
    "bg-red-500",
    "from-red-500",
    "to-red-500",
    "to-red-600",
    "bg-blue-500",
    "from-blue-500",
    "to-blue-500",
    "bg-yellow-300",
    "via-yellow-300",
    // Typography and font classes
    "prose",
    "prose-slate",
    "prose-lg",
    "prose-dark",
    "font-heading",
    "font-heading-alt",
    "font-display",
    "font-display-alt",
    "font-small-caps",
    "font-body",
    // Icon classes
    "i-ph-anchor-simple-thin",
    "i-mdi-alarm",
    "i-logos-vue",
    "i-carbon-sun",
    "i-carbon-moon",
    "i-twemoji-grinning-face-with-smiling-eyes",
    "i-twemoji-face-with-tears-of-joy",
    "i-heroicons-heart",
    "i-heroicons-home",
    "i-heroicons-user",
    "i-heroicons-cog",
    "i-heroicons-star",
    "i-heroicons-bell",
    "i-heroicons-search",
    "i-heroicons-mail",
  ],
});
