version: '3.8'
services:
    postgres:
        container_name: pyromancy-prisma-api
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_DB=mydb
            - POSTGRES_USER=gbtunney
            - POSTGRES_PASSWORD=randompassword
            - POSTGRES_PORT=5432
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - '5432:5432'
volumes:
    postgres:
